### ISSUE TITLE
Research Light Frequency Patterns

### ISSUE THREAD

**Issue by SirMatthew74** [cybernaut-neko/flickerguard#41]
We need some basic information about light frequencies to find out what the hardware requirements are:

Research Topics:

1. Common commercial lighting flicker rates.
2. Common screen and monitor flicker rates.
3. Known frequencies that cause seizures.

I will assume that flicker rates will probably be harmonically related to known blink rates that cause seizures.  EEG tests have a strobe.  I think I read somewhere that these were very low.  Anyhow, you can obviously see them blink.  People seem to have sensitivities to much higher rates, ones you can't see.  My suspicion is that the higher rates are multiples of the lower rates.  IDK if this is true, but I'll see what I can find.

**Comment by cybernaut-neko** [comment]
Screens are between 60 and 240 Hrz ( one 500hrz ) in my experience the 60Hrz can be a problem form 90 and above I never had any problems unless I scrolled a bit fast, so I use high refresh rate gaming monitors.

**Comment by cybernaut-neko** [comment]
Closed, see wiki, but will make a new discussion item relating to this.
